CREATE TABLE ADMIN(ADMIN_ID INTEGER PRIMARY KEY AUTOINCREMENT,ADMIN_NAME VARCHAR(255) NOT NULL,ADMIN_EMAIL VARCHAR(255) NOT NULL UNIQUE
,ADMIN_PASSWORD VARCHAR(255) NOT NULL);

CREATE TABLE FINE_TICKETS(FINE_ID INTEGER PRIMARY KEY AUTOINCREMENT,FINE_DESCRIPTION VARCHAR(255),FINE_AMOUNT DECIMAL(10,2) NOT NULL);

CREATE TABLE VIOLATIONS(NOTICE_ID INTEGER PRIMARY KEY AUTOINCREMENT,VEHICLE_ID INTEGER,FOREING KEY(VEHICLE_ID) REFERENCES VIHICLE(VEHICLE_ID) 
ON DELETE CASCADE,FINE_ID INTEGER,FOREIGN KEY(FINE_ID) REFERENCES FINE_TICKETS(FINE_ID) ON DELETE CASCADE,FINE_ID INTEGER,
FOREIGN KEY(OFFICER_ID) REFERENCES TPO(OFFICER_ID) SET NULL,PLACE VARCHAR(255) NOT NULL,
DATE DATETIME,STATUS VARCHAR(8) NOT NULL DEFAULT 'NOT PAID');

CREATE TABLE VEHICLE(VEHICLE_ID INTEGER DEFAULT 1000 PRIMARY KEY AUTOINCREMENT,LICENSE_NUMBER VARCHAR(10) UNIQUE,VEHICLE_TYPE VARCHAR(255) NOT NULL,VEHICLE_MODEL 
VARCHAR(255) NOT NULL,COLOR VARCHAR(10),OWNER_ID VARCHAR(50),FOREIGN KEY(OWNER_ID) REFERENCES OWNER(OWNER_ID) SET NULL);

CREATE TABLE OWNER(OWNER_ID INTEGER PRIMARY KEY AUTOINCREMENT,OWNER_NAME VARCHAR(255) NOT NULL,DL_NO VARCHAR(15) NOT NULL UNIQUE,PHONE_NO 
BIGINT NOT NULL UNIQUE,OWNER_EMAIL VARCHAR(255) NOT NULL UNIQUE);

CREATE TABLE TPO (OFFICER_ID INTEGER PRIMARY KEY,OFFICER_NAME VARCHAR(255) NOT NULL,OFFICER_EMAIL VARCHAR(255) NOT NULL UNIQUE,
POLICE_STATION VARCHAR(255) NOT NULL);