CREATE TABLE ADMIN(ADMIN_ID INTEGER PRIMARY KEY AUTO_INCREMENT,ADMIN_NAME VARCHAR(255) NOT NULL,ADMIN_EMAIL 
VARCHAR(255) NOT NULL UNIQUE,ADMIN_PASSWORD VARCHAR(16) NOT NULL);

CREATE TABLE FINE_TICKETS(FINE_ID INTEGER PRIMARY KEY AUTOINCREMENT,FINE_DESCRIPTION VARCHAR(255),FINE_AMOUNT 
DECIMAL(10,2) NOT NULL);

CREATE TABLE VIOLATIONS(NOTICE_ID INTEGER PRIMARY KEY AUTOINCREMENT,VEHICLE_ID INTEGER,FOREING KEY(VEHICLE_ID) 
REFERENCES VIHICLE(VEHICLE_ID) ON DELETE CASCADE,FINE_ID INTEGER,FOREIGN KEY(FINE_ID) REFERENCES FINE_TICKETS
(FINE_ID) ON DELETE CASCADE,FINE_ID INTEGER,FOREIGN KEY(OFFICER_ID) REFERENCES TPO(OFFICER_ID) SET NULL,PLACE 
VARCHAR(255) NOT NULL,DATE DATETIME,STATUS VARCHAR(8) NOT NULL DEFAULT 'NOT PAID');

CREATE TABLE VEHICLE(VEHICLE_ID INTEGER PRIMARY KEY AUTO_INCREMENT,LICENSE_NUMBER VARCHAR(10) NOT NULL 
UNIQUE,VEHICLE_TYPE VARCHAR(255) NOT NULL,VEHICLE_MODEL VARCHAR(255) NOT NULL,OWNER_ID INTEGER,
FOREIGN KEY(OWNER_ID) REFERENCES OWNER(OWNER_ID) ON DELETE SET NULL);

INSERT INTO VEHICLE(LICENSE_NUMBER,VEHICLE_TYPE,VEHICLE_MODEL,OWNER_ID) VALUES
("SDJIOF938","SODNFWEW","SDFNWEU",8),
("SDFNE238","KMWOE","FNWEFIUWEN",11),
("KMDFO8923","FFIWEH","NJIFIWEN",8);

CREATE TABLE OWNER(OWNER_ID INTEGER PRIMARY KEY AUTO_INCREMENT,OWNER_NAME VARCHAR(255) NOT NULL,DL_NO VARCHAR(15) 
NOT NULL UNIQUE,OWNER_EMAIL VARCHAR(255) NOT NULL UNIQUE,PHONE_NO BIGINT NOT NULL UNIQUE);

INSERT INTO OWNER(OWNER_NAME,DL_NO,OWENR_EMAIL,PHONE_NO) VALUES
("WOENFSDF,SK8293812,SAFJOWIE@SWEF,384298923"),
("SKDNWIE JIOFWE,KD924892,LMKOW@SWOIEJ,989283891"),
("SDNFWIEF,WID490382,8SDNFW3@JFWIOE,2932831");

CREATE TABLE TPO (OFFICER_ID INTEGER PRIMARY KEY AUTO_INCREMENT,OFFICER_NAME VARCHAR(255) NOT NULL,OFFICER_EMAIL 
VARCHAR(255) NOT NULL UNIQUE,OFFICER_PASSWORD VARCHAR(16) NOT NULL,POLICE_STATION VARCHAR(255) NOT NULL);

INSERT INTO TPO(OFFICER_NAME,OFFICER_EMAIL,OFFICER_PASSWORD,POLICE_STATION) VALUES
("IWENF","WEOIFEN@SIF","WIENF2398","SFIJSNFIW"),
("JWIENF","EWINF@SD","SFWIE9238","SIWEW EWIN"),
("SDFNWEU","WEN923@SDINFI","FWEUNW2938","WEN INW");